simple_rover_locomotion_node:
    ros__parameters:
        enable_pose_name: "NONE"
        disable_pose_name: "stowed"

        # Names corresponding to the steering (str) and deployment (dep) positions:
        # Must be different lists, since not all rovers have only steerable wheels.
        str_names: ['LF', 'RF', 'LC', 'RC', 'LR', 'RR']
        dep_names: ['LF', 'RF', 'LC', 'RC', 'LR', 'RR']

        # Rover poses saved as joint positions in [rad]
        poses:
          straight:
            str_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
            dep_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
          stowed:
            str_positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
            dep_positions: [1.57, 1.57, 1.57, 1.57, 1.57, 1.57]
          point_turn:
            str_positions: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
            dep_positions: [1.57, 1.57, 1.57, 1.57, 1.57, 1.57]